http:
  port: "8081"
 
sfdc:
  username: "chauhanmanoj16358-zece@force.com"
  passward: "Ranachauhan@123"
  token: "VbH3tQ8QlXlA27pnNQUkm1bhQ"
  
file:
  accountsDir: "C:/mulesoft software/APDevFundamentals_studentFiles_SP_04may2023/resources"

db:
  host: "mudb.learn.mulesoft.com"
  port: "3306"
  user: "mule"
  password: "mule"
  database: "training"